## Mark Shust's Docker Configuration for Magento
## (https://github.com/markshust/docker-magento)
##
## Version 44.0.0

## To use SSH, see https://github.com/markshust/docker-magento#ssh
## Linux users, see https://github.com/markshust/docker-magento#linux

## If you changed the default Docker network, you may need to replace
## 172.17.0.1 in this file with the result of:
## docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}'

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.18-8
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.lixil.rule=Host(`lixil.test`)"
      - "traefik.http.routers.lixil.entrypoints=websecure"
      - "traefik.http.routers.lixil.tls=true"
      - "traefik.http.services.lixil-service.loadbalancer.server.port=8443"
      - "traefik.http.services.lixil-service.loadbalancer.server.scheme=https"
      - "traefik.http.services.lixil-service.loadbalancer.serversTransport=mytransport@file"
    extra_hosts: &appextrahosts
      - "host.docker.internal:host-gateway"
      ## Selenium support, replace "magento.test" with URL of your site
      #- "magento.test:172.17.0.1"
    networks:
      - proxy
      - default

  phpfpm:
    image: markoshust/magento-php:8.1-fpm-1
    volumes: *appvolumes
    env_file: env/phpfpm.env
    networks:
      - default
    #extra_hosts: *appextrahosts

  db:
    image: mariadb:10.4
    hostname: db-lixil
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - default
      - database

  redis:
    image: redis:6.2-alpine
    networks:
      - default

  opensearch:
    image: markoshust/magento-opensearch:1.2-0
    env_file: env/opensearch.env
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
    networks:
      - default

  rabbitmq:
    image: markoshust/magento-rabbitmq:3.9-0
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: env/rabbitmq.env
    networks:
      - default
  
  ## Blackfire support, uncomment to enable
  #blackfire:
  #  image: blackfire/blackfire:2
  #  ports:
  #    - "8307"
  #  env_file: env/blackfire.env

  ## Selenium support, uncomment to enable
  #selenium:
  #  image: selenium/standalone-chrome-debug:3.8.1
  #  ports:
  #    - "5900:5900"
  #  extra_hosts: *appextrahosts

volumes:
  appdata:
  dbdata:
  sockdata:
  ssldata:
  rabbitmqdata:

networks:
  proxy:
    external: true
  database:
    external: true