version:  '3'

services:
  reverse-proxy:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/static.yml:/etc/traefik/traefik.yml:ro"
      - "./config/dynamic.yml:/etc/traefik/dynamic.yml:ro"
      - "./certs:/etc/certs:ro"
    networks:
       - proxy
  
  adminer:
    image: adminer
    ports:
      - 81:8080
    networks:
      - database

  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"
    networks:
      - proxy

networks:
  proxy:
    external: true
  database:
    external: true